// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZvFzgCY0yd-znvjx7vpaQzyxacYoErk0',
    appId: '1:515394464324:web:8aba9768497926d74dea11',
    messagingSenderId: '515394464324',
    projectId: 'sample-project-b2cd9',
    authDomain: 'sample-project-b2cd9.firebaseapp.com',
    storageBucket: 'sample-project-b2cd9.appspot.com',
    measurementId: 'G-MCEG5KP2T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeLm90lxSZhYQfbAWk76JcogQBcJuKs2A',
    appId: '1:515394464324:android:098cca2fc01a12f14dea11',
    messagingSenderId: '515394464324',
    projectId: 'sample-project-b2cd9',
    storageBucket: 'sample-project-b2cd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSrV4SSks08yvdmx6Zz3l6rBSgk_AbmVk',
    appId: '1:515394464324:ios:db234e6ef3c17a814dea11',
    messagingSenderId: '515394464324',
    projectId: 'sample-project-b2cd9',
    storageBucket: 'sample-project-b2cd9.appspot.com',
    iosClientId: '515394464324-2uteitac2qsdh47rkqtq1u0ho794baq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSrV4SSks08yvdmx6Zz3l6rBSgk_AbmVk',
    appId: '1:515394464324:ios:2ceda41cbf4481144dea11',
    messagingSenderId: '515394464324',
    projectId: 'sample-project-b2cd9',
    storageBucket: 'sample-project-b2cd9.appspot.com',
    iosClientId: '515394464324-br6g946vpj63jtt5vd608bu4e2k3iop2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat.RunnerTests',
  );
}
